apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-topic
  labels:
    strimzi.io/cluster: ephemeral
spec:
  topicName: test-topic
  partitions: 4
  replicas: 1
  config:
    retention.ms: 7200000
---