apiVersion: kafkaconnect.operator.io/v1alpha1
kind: KafkaConnectAutoScaler
metadata:
  name: example-kafkaconnectautoscaler
spec:
  kcScaleTargetRef:
    apiVersion: kafkaconnect.operator.io/v1alpha1
    name: experiment-ssp
    kafkaConnectorName: connector-elastic
  minTasks: 1
  maxTasks: 4
  metrics:
  - type: Object
    object:
      describedObject: 
        kind: KafkaConnect
        name: experiment-ssp
        apiVersion: kafkaconnect.operator.io/v1alpha1
      metric:
        name: connector-elastic-lag
      target:
        type: Value
        value: "10"
